name: Publish to NPM
on:
  release: 
    types: [created]
jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.19.0'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install dependencies and build 🔧
        run: npm ci && npm run build
      - name: Publish to NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions: 
      contents: read
      id-token: write